### ISSUE TITLE
Change input parameters testing

### ISSUE THREAD

**Issue by vecernik** [timdeschryver/ngx-testing-library#1]
I just found this lib and I love it for OnPush testing. Is there a way to change component's @Input() parameters and assert the changes it makes? 

That could allow to createComponent() only once and test() only changes made to Inputs. 

This currently doesn't work (using tpl "<span *ngIf="isOpened">Opened</span>"): 

expect(createdComponent.getByText('Opened')).not.toBeDefined() // THIS WORKS with isOpened=false or undefined

createdComponent.componentInstance.isOpened = true // changing @Input() parameter
createdComponent.fixture.detectChanges()  // usually necessary 
expect(createdComponent.getByText('Opened')).toBeDefined() // THIS FAILS

**Comment by timdeschryver** [comment]
Hi @vecernik ! Thanks for the feedback.
Have you tried it with `createdComponent.fixture.detectChanges()`?
Because this isn't done automatically for you, only if you would do `click(createdComponent.getByText('toggle'))` (which I recommend to do).

**Comment by vecernik** [comment]
Unfortunately, detectChanges() has no effect, probably because of changeDetection: ChangeDetectionStrategy.OnPush of the component.

It looks like with OnPush, attributes must be defined in a host component scope, then passed to a tested component as inputs. Then, changes should be propagated from a host component scope to a tested component and rerendered.

**Comment by timdeschryver** [comment]
I'll try to take a look later this week, feel free to take a stab at it too ;)

**Comment by timdeschryver** [comment]
I was able to reproduce it and it seems like you're right.
Also, it's working if you do the following
 ```ts
click(getByText('Toggle'));
``` 
instead of
 ```ts
createdComponent.componentInstance.isOpened = true;
```

**Comment by timdeschryver** [comment]
I've given it a bit more thought and I think this won't be added, because this goes against the ideas and principles of this library. If you want to toggle the `isOpened` in your use case you should do this by triggering an event, just like your users would do. 

If you would want to toggle `isOpened` programmaticaly you'll have to inject `ChangeDetectorRef` in your component and trigger the change detection via it.

```ts
// toggle.ts
export class ToggleComponent {
  @Input() isOpen;
  constructor(public changeRef: ChangeDetectorRef) {}
}

// toggle.spec.ts
test('toggles isOpen', async () => {
  const { queryByText, fixture } = await createComponent('<toggle></toggle>', {
    declarations: [ToggleComponent],
  });

  const toggleComponent = fixture.debugElement.query(By.directive(ToggleComponent))
    .componentInstance as ToggleComponent;

  expect(queryByText('Open')).toBeNull();
  toggleComponent.isOpen = true;
  toggleComponent.changeRef.detectChanges();
  expect(queryByText('Open')).toBeDefined();
});
```
